/**
 * Gare estratte dal Calendario Corse province Va-Mi-No-Vb-Co-Bi-Vc-Mb-PV-Lc.
 * distance, time, infoUrl sono opzionali (alcune gare non li hanno).
 */
export type CalendarRaceEntry = {
  date: string;
  type: string;
  name: string;
  location: string;
  province?: string | null;
  distance?: string | null;
  time?: string | null;
  infoUrl?: string | null;
};

export const CALENDAR_RACES: CalendarRaceEntry[] = [
  { date: "2026-02-07", type: "CROSS", name: "3° tappa Campionato Brianzolo di Corsa Campestre", location: "AGRATE BRIANZA", province: "MB", distance: "6/3", time: "14.30", infoUrl: "www.campionatobrianzolo.it" },
  { date: "2026-02-07", type: "CROSS", name: "Cross Città di Oleggio", location: "OLEGGIO", province: "NO", distance: "6/4", time: "15.30", infoUrl: "www.piemonte.fidal.it" },
  { date: "2026-02-07", type: "TRAIL", name: "Urban Night Trail", location: "BERGAMO", province: "BG", distance: "12.5", time: "18.00", infoUrl: "www.followyourpassion.it" },
  { date: "2026-02-07", type: "STRADA", name: "Parkrun", location: "MILANO", province: "MI", distance: "5", time: "9.00", infoUrl: "www.parkrun.it/milanonord/" },
  { date: "2026-02-08", type: "MEZZA", name: "Città di Vercelli Half Marathon (rinviata al 26/04)", location: "VERCELLI", province: "VC", distance: "21.097/10", time: "9.30", infoUrl: "www.circuitorunning.it" },
  { date: "2026-02-08", type: "TRAIL", name: "Winter Brich Trail Valdengo", location: "VALDENGO", province: "BI", distance: "42/23/13/9", time: null, infoUrl: "www.winterbrichtrail.it" },
  { date: "2026-02-08", type: "CROSS", name: "3° tappa Cross per tutti", location: "LISSONE", province: "MB", distance: "6/4", time: "9.00", infoUrl: "www.crosspertutti.it" },
  { date: "2026-02-08", type: "MEZZA", name: "Bergamo21", location: "BERGAMO", province: "BG", distance: "21.097/10", time: "9.00", infoUrl: "www.followyourpassion.it" },
  { date: "2026-02-08", type: "CROSS", name: "Trofeo Lanfritto Maggioni", location: "ALBATE", province: "CO", distance: "4/3", time: "9.30", infoUrl: "www.fidal-lombardia.it" },
  { date: "2026-02-08", type: "CROSS", name: "Cross della Vernavola", location: "PAVIA", province: "PV", time: "9.15", infoUrl: null },
  { date: "2026-02-14", type: "CROSS", name: "4° tappa Campionato Brianzolo di Corsa Campestre", location: "MONZA PARCO", province: "MB", distance: "6/3", time: "14.30", infoUrl: "www.campionatobrianzolo.it" },
  { date: "2026-02-14", type: "STRADA", name: "Mongrando in alto", location: "MONGRANDO", province: "BI", distance: "5.6", infoUrl: "www.piemonte.fidal.it" },
  { date: "2026-02-14", type: "STRADA", name: "Karneval Run", location: "BIELLA", province: "BI", distance: "5/3", time: "15.30", infoUrl: "www.irunning.it" },
  { date: "2026-02-15", type: "TRAIL", name: "Trail delle Terre di Mezzo", location: "DAVERIO", province: "VA", distance: "22/12", time: "9.30", infoUrl: "www.traildelleterredimezzo.it" },
  { date: "2026-02-15", type: "STRADA", name: "Arona 10k", location: "ARONA", province: "NO", distance: "10/5", time: "9.30", infoUrl: "www.podisticaarona.it" },
  { date: "2026-02-15", type: "STRADA", name: "Sozzago in Love", location: "SOZZAGO", province: "NO", distance: "10/5", time: "9.00", infoUrl: "www.atleticatrecate.it" },
  { date: "2026-02-15", type: "CROSS", name: "Cross sociale", location: "PIOLTELLO", province: "MI", distance: "4", time: "10.30", infoUrl: null },
  { date: "2026-02-21", type: "STRADA", name: "Salomon New shapers run", location: "MILANO", province: "MI", distance: "10", time: "11.00", infoUrl: null },
  { date: "2026-02-22", type: "STRADA", name: "Corriamo per il Kenya", location: "CAMERI", province: "NO", distance: "9/14.2", time: "9.30", infoUrl: null },
  { date: "2026-02-22", type: "MEZZA", name: "Maratonina di Treviglio", location: "TREVIGLIO", province: "BG", distance: "21.097", infoUrl: null },
  { date: "2026-02-22", type: "TRAIL", name: "Piatto Trail", location: "LENTA", province: "VC", distance: "14/7/2", time: "9.30", infoUrl: "www.circuitoviola.org" },
  { date: "2026-02-22", type: "CROSS", name: "Trofeo Lanfritto Maggioni", location: "CASNATE CON BERNATE", province: "CO", infoUrl: "www.fidal-lombardia.it" },
  { date: "2026-02-22", type: "CROSS", name: "Cross di Moncrivello", location: "MONCRIVELLO", province: "VC", distance: "6/4", time: "9.30", infoUrl: "www.atleticando.net" },
  { date: "2026-02-28", type: "CROSS", name: "5° tappa Campionato Brianzolo di Corsa Campestre", location: "BRIOSCO", province: "MB", distance: "6/3", time: "14.30", infoUrl: "www.campionatobrianzolo.it" },
  { date: "2026-02-28", type: "TRAIL", name: "Trail dell'Alpino", location: "GOZZANO", province: "NO", distance: "15/5", time: "15.00", infoUrl: null },
  { date: "2026-03-01", type: "STRADA", name: "Puma Ten", location: "CASORATE SEMPIONE", province: "VA", distance: "10/5", time: "9.00", infoUrl: "www.atletica-casorate.it" },
  { date: "2026-03-01", type: "CROSS", name: "4° tappa Cross per tutti", location: "CINISELLO BALSAMO", province: "MI", distance: "6/4", time: "9.00", infoUrl: "www.crosspertutti.it" },
  { date: "2026-03-01", type: "G. D'ORO", name: "Gamba d'Oro – Memorial Manfron", location: "SERRAVALLE SESIA", province: "VC", distance: "10/1.5", time: "9.00", infoUrl: null },
  { date: "2026-03-01", type: "MEZZA", name: "Lecco City Half Marathon", location: "LECCO", province: "LC", distance: "21.097", infoUrl: null },
  { date: "2026-03-01", type: "TRAIL", name: "Trail Monte Sangiano", location: "SANGIANO", province: "VA", distance: "7/14/21", time: "9.00", infoUrl: "www.atletica3v.it" },
  { date: "2026-03-01", type: "TRAIL", name: "Trail del Mastrolino", location: "OMEGNA", province: "VB", distance: "21/10", time: "10.00", infoUrl: null },
  { date: "2026-03-07", type: "TRAIL", name: "Campo dei Fiori Trail", location: "GAVIRATE", province: "VA", distance: "70/50/38", time: "6.00", infoUrl: "www.campodeifioritrail.it" },
  { date: "2026-03-07", type: "CROSS", name: "6° tappa Campionato Brianzolo", location: "CARATE BRIANZA", province: "MB", distance: "6/3", time: "14.30", infoUrl: "www.campionatobrianzolo.it" },
  { date: "2026-03-08", type: "TRAIL", name: "Campo dei Fiori Trail", location: "GAVIRATE", province: "VA", distance: "28/12", time: "8.00", infoUrl: "www.campodeifioritrail.it" },
  { date: "2026-03-08", type: "MEZZA", name: "Lago Maggiore Half Marathon", location: "STRESA", province: "VB", distance: "21.097/10", time: "10.00", infoUrl: "www.lmhm.it" },
  { date: "2026-03-08", type: "MEZZA", name: "Run for Life", location: "MONZA", province: "MB", distance: "21.097/10", infoUrl: "www.runforlifeitaly.it" },
  { date: "2026-03-08", type: "CROSS", name: "5° tappa Cross per tutti", location: "BRUGHERIO", province: "MB", distance: "6/4", time: "9.00", infoUrl: "www.crosspertutti.it" },
  { date: "2026-03-08", type: "STRADA", name: "2 City 4 Run", location: "BUSTO ARSIZIO", province: "VA", distance: "9.9", time: "9.30", infoUrl: "www.sportpiu.org" },
  { date: "2026-03-15", type: "MEZZA", name: "Scarpadoro Half Marathon", location: "VIGEVANO", province: "PV", distance: "21.097/10.2/4", time: "9.30", infoUrl: "www.scarpadoro.it" },
  { date: "2026-03-15", type: "P. D'ORO", name: "Marciando per la Vita", location: "VARESE", province: "VA", distance: "9.5/4.4", time: "9.00", infoUrl: "www.piededoro.it" },
  { date: "2026-03-15", type: "STRADA", name: "Corsa dei 3 parchi", location: "MILANO PARCO DELLE CAVE", province: "MI", distance: "20/12/5", time: "9.00", infoUrl: null },
  { date: "2026-03-22", type: "STRADA", name: "DK Race 10k", location: "MONZA", province: "MB", distance: "10", time: "9.00", infoUrl: "www.fidal-lombardia.it" },
  { date: "2026-03-22", type: "STRADA", name: "Corsa del Viandante", location: "ABBADIA LARIANA", province: "LC", distance: "10", time: "9.45", infoUrl: null },
  { date: "2026-03-22", type: "STRADA", name: "RunDamiano", location: "COGLIATE", province: "MB", distance: "9.9/5", time: "9.00", infoUrl: "www.rundamiano.com" },
  { date: "2026-03-22", type: "P. D'ORO", name: "Arsalonga", location: "ARSAGO", province: "VA", distance: "10.5/5", time: "9.00", infoUrl: "www.piededoro.it" },
  { date: "2026-03-29", type: "P. D'ORO", name: "Grand Prix della Valbossa", location: "AZZATE", province: "VA", distance: "10/4", time: "9.00", infoUrl: "www.piededoro.it" },
  { date: "2026-03-29", type: "TRAIL", name: "Trail del Barro", location: "INVORIO", province: "NO", distance: "11/25", infoUrl: "www.volpinvorio.com" },
  { date: "2026-03-29", type: "STRADA", name: "La velocissima", location: "ARESE", province: "MI", distance: "10", time: "8.30", infoUrl: "www.aresegtv.it" },
  { date: "2026-04-12", type: "Maratona", name: "Milano Marathon", location: "MILANO", province: "MI", distance: "42.195", infoUrl: "www.milanomarathon.it" },
  { date: "2026-04-12", type: "MEZZA", name: "Mezza dei 2 laghi", location: "GRAVELLONA TOCE", province: "VB", distance: "21.097/10", time: "9.00", infoUrl: "www.mezza2laghi.it" },
  { date: "2026-04-12", type: "TRAIL", name: "Rasa Ultra Marathon Trail", location: "RASA", province: "VA", distance: "42/21/6h", time: "7.00", infoUrl: null },
  { date: "2026-04-18", type: "STRADA", name: "Milano 10k", location: "MILANO IDROSCALO", province: "MI", distance: "10", time: "19.15", infoUrl: "www.followyourpassion.it" },
  { date: "2026-04-19", type: "TRAIL", name: "Ossola Trail", location: "MERGOZZO", province: "VB", distance: "28/20/10", time: "9.00", infoUrl: "www.ossolatrail.com" },
  { date: "2026-04-19", type: "STRADA", name: "Brunellissima", location: "BRUNELLO", province: "VA", distance: "10/5", infoUrl: "www.prolocobrunello.it" },
  { date: "2026-04-19", type: "STRADA", name: "Liuc Run", location: "CASTELLANZA", province: "VA", distance: "10/5", time: "9.30", infoUrl: "www.sportpiu.org" },
  { date: "2026-04-26", type: "MEZZA", name: "Città di Vercelli Half Marathon", location: "VERCELLI", province: "VC", distance: "21.097/10", time: "9.30", infoUrl: "www.circuitorunning.it" },
  { date: "2026-04-26", type: "TRAIL", name: "Trail del Soldato Franz", location: "CUVIO", province: "VA", distance: "25/12", time: "9.00", infoUrl: null },
  { date: "2026-04-26", type: "MEZZA", name: "Eco Run Varese", location: "VARESE", province: "VA", distance: "21.097/10", time: "9.00", infoUrl: "www.ecorunvarese.it" },
  { date: "2026-05-03", type: "MEZZA", name: "Stramilano", location: "MILANO", province: "MI", distance: "21.097/10/5", time: "8.30", infoUrl: "www.stramilano.it" },
  { date: "2026-05-03", type: "P. D'ORO", name: "Life Run 10 Gallarate", location: "GALLARATE", province: "VA", distance: "10/5", time: "9.00", infoUrl: "www.piededoro.it" },
  { date: "2026-05-10", type: "P. D'ORO", name: "Athlon Run", location: "CASTIGLIONE OLONA", province: "VA", distance: "9.9/5", time: "9.00", infoUrl: "www.piededoro.it" },
  { date: "2026-05-17", type: "P. D'ORO", name: "Besozzo Running", location: "BESOZZO", province: "VA", distance: "10/4.5", time: "9.00", infoUrl: "www.piededoro.it" },
  { date: "2026-05-24", type: "P. D'ORO", name: "Camminiamo insieme", location: "COQUIO TREVISAGO", province: "VA", distance: "8.5/3.5", time: "9.00", infoUrl: "www.piededoro.it" },
  { date: "2026-05-31", type: "STRADA", name: "Magenta Run 10k", location: "MAGENTA", province: "MI", distance: "10", infoUrl: "www.circuitorunning.it" },
  { date: "2026-05-31", type: "P. D'ORO", name: "Quater pass Inturna a Maria Bambina", location: "VILLADOSIA", province: "VA", distance: "10/5", time: "9.00", infoUrl: "www.piededoro.it" },
  { date: "2026-06-07", type: "P. D'ORO", name: "Corri sotto la rocca di Angera", location: "ANGERA", province: "VA", distance: "10/5/1", time: "9.00", infoUrl: "www.piededoro.it" },
  { date: "2026-06-13", type: "P. D'ORO", name: "Brennight", location: "BRENNO USERIA", province: "VA", distance: "6/4", time: "20.00", infoUrl: "www.piededoro.it" },
  { date: "2026-06-21", type: "P. D'ORO", name: "Stramaccagno", location: "MACCAGNO", province: "VA", distance: "10/4", time: "9.00", infoUrl: "www.piededoro.it" },
  { date: "2026-07-05", type: "P. D'ORO", name: "Quatar Pass par Arcisà", location: "ARCISATE", province: "VA", distance: "9/4", time: "9.00", infoUrl: "www.piededoro.it" },
  { date: "2026-09-13", type: "P. D'ORO", name: "Corri e cammina a Cantello", location: "CANTELLO", province: "VA", distance: "10/5", time: "9.00", infoUrl: "www.piededoro.it" },
  { date: "2026-09-27", type: "MEZZA", name: "Corripavia Half Marathon", location: "PAVIA", province: "PV", distance: "21.097", infoUrl: "www.corripavia.it" },
  { date: "2026-10-04", type: "MEZZA", name: "Agnoletto Half Marathon", location: "NOVARA", province: "NO", distance: "21.097", infoUrl: "www.newrt.it" },
  { date: "2026-10-04", type: "MEZZA", name: "Monza Half Marathon", location: "MONZA", province: "MB", distance: "21.097", infoUrl: "www.followyourpassion.it" },
  { date: "2026-10-11", type: "P. D'ORO", name: "Witch Run", location: "VENEGONO", province: "VA", distance: "10/5", time: "9.00", infoUrl: "www.piededoro.it" },
  { date: "2026-10-18", type: "P. D'ORO", name: "Cross Country dei 7 campanili", location: "CAVARIA", province: "VA", distance: "15.6/4.5", time: "9.00", infoUrl: "www.piededoro.it" },
  { date: "2026-10-25", type: "MEZZA", name: "Laus Half Marathon", location: "LODI", province: "LO", distance: "21.097", infoUrl: "www.laushalfmarathon.it" },
  { date: "2026-10-25", type: "MEZZA", name: "Varese City Run", location: "VARESE", province: "VA", distance: "21.097/10", infoUrl: "www.sportpiu.org" },
  { date: "2026-11-08", type: "MEZZA", name: "Maratonina Città di Busto Arsizio", location: "BUSTO ARSIZIO", province: "VA", distance: "21.097", infoUrl: "www.maratoninadibusto.it" },
  { date: "2026-11-22", type: "CROSS", name: "5 mulini", location: "SAN VITTORE OLONA", province: "MI", infoUrl: "www.cinquemulini.org" },
  { date: "2026-11-22", type: "MEZZA", name: "Milano Half Marathon Milano 21", location: "MILANO", province: "MI", distance: "21.097/10", infoUrl: "www.followyourpassion.it" },
];
